<?php
	$title = 'NE/IA Saint Bernard Rescue - About Us';
	$nav = 'about';
?>
<?php require_once("includes/top.php"); ?> 
<?php require_once("includes/navbar.php"); ?>
    
    <div id="content_main">
        <h2>National Saint Bernard Rescue Foundation, Inc.</h2>
        <h3>Mission</h3>
        <p>To act as a shepherd for Saint Bernard dogs and puppies that are without suitable caretakers and are in need of help; to shelter the homeless; to care for and find homes for the unwanted, abandoned, neglected and abused; to feed the hungry; to provide medical services to the sick, injured and lame; to assist in the rescue of those subjected to conditions hazardous to their well-being or to confinement in government or private shelter, who without intervention would be needlessly Euthanize; to provide for the humane disposition of those not sound in mind, body or temperament; to educate the public as to the characteristics of, and proper care for, the breed so as to promote compatible, loving, lasting home/family placements; to educate the public as to responsible pet ownership so as to prevent accidental litters and to prevent inhumane trafficking in puppies and dogs, and so as to promote the most humane manner of disposition of pets at journey's end; to encourage, promote and support research respecting the breed that explores or improves relations between the breed and owners or sheds light on the causes of abandonment, neglect or abuse, or promotes the public's understanding of the special characteristics and attributes of the breed or that is designed to improve the welfare of the breed in any manner. Though the Foundation is established to provide services primarily to the Saint Bernard, the foundation will not refuse services to any dog in need of immediate and caring attention.</p>
        <h2>NE/IA Saint Bernard Rescue</h2>
        <h3>Who We Are</h3>
        <p>The Saint Bernard Rescue Foundation, Inc., is a nationwide, all-volunteer, non-profit, tax-exempt, 501(c)(3) charitable organization. Our Foundation operates nationally, facilitating a network of volunteers in nearly every state of the union. We are the exclusively endorsed rescue program of the Saint Bernard Club of America.</p>
        <h3>Our Mission</h3> 
        <p>Our mission is to help rescue homeless, abandoned (often neglected and abused) Saint Bernard puppies and dogs, and find loving, permanent homes. Our mission has both a rescue plank and an education plank. Our rescue program is necessary to save dogs in peril today; our education objectives are necessary to change public attitudes and behaviors so that we can attack the plague at its source: irresponsible breeding and treatment of these loving animals. Though the Foundation is established to provide services primarily to the Saint Bernard, the Foundation will not refuse services to any dog in need of immediate and caring attention.</p>
        <h3>The Need</h3>
        <p>Each year there are untolled millions of puppies and dogs that are euthanized, usually for the simple reason that they are no longer wanted by their families that will not bother to try to locate a new home. There unwanted companions are treated as disposable property. Knowledgeable authorities indicate that nearly half (40%) of all dogs that wind up in animal shelters and humane societies are purebred dogs. These figures tell us that if every breed club were able to implement a successful rescue program, the casualties of this cruel plague (humans unto canine) could be cut nearly in half. And if every breeder, of pure or mixed breed, would take responsibility to commit to finding loving, permanent homes for every dog they breed, we could eradicate this plague altogether.</p>
        <h3>What We Do</h3>
        <p>We assist grass-roots local rescue groups )all are comprised of volunteers) by (a) providing funding for food, shelter, transportation, medical, etc. as needed to support the local rescue operations of groups or individuals that do not have adequate funding to cover their operations; (b) allowing them to use, where available, a Foundation-owned and operated dog sanctuary to care for the dogs while loving homes are sought for adoption placements; (c) providing free education services to rescue volunteers, and (d) serving as an information clearinghouse for rescue nationally.</p>
        <h3>Successful Journey</h3> 
        <p>It is a most rewarding experience to see a rescue dog go to its new home and become a cherished member of the family. Prior to our incorporation in 1998, the count of dogs saved annually started in the hundreds, with approximately 350 Saints saved the first year of the Foundation's operations. Just three and one-half years later, the annual count starts in excess of a thousand. We have seen nearly every type of abuse and neglect imaginable. With the help of volunteers and supporters, the Foundation is available and able to help when these dogs are found in need. Every successful journey leads to the same destination; a lasting, loving home.</p>
    </div> <!--ENDS CONTENT_MAIN DIV-->
    
<?php require_once("includes/site_info.php"); ?>