<?php
	$title = "NE/IA Saint Bernard Rescue - FAQ's";
	$nav = '';
?>
<?php require_once("includes/top.php"); ?> 
<?php require_once("includes/navbar.php"); ?>
    
    <div id="content_main">
    	<a name="top" id="top"></a>
   	  <h2>Frequently Asked Questions</h2>
        <ul>
        	<li><a href="#eat">How much do they eat?</a></li>
            <li><a href="#weight">How much do they weigh?</a></li>
            <li><a href="#children">Are they good with children?</a></li>
            <li><a href="#train">Are they easy to train?</a></li>
            <li><a href="#shed">Do they shed?</a></li>
            <li><a href="#drool">Do they drool?</a></li>
            <li><a href="#glands">Is it OK to clip a Saints saliva glands?</a></li>
            <li><a href="#watchdog">Are they good watch dogs?</a></li>
            <li><a href="#shorthair">Why do some Saint Bernards have short hair?</a></li>
            <li><a href="#room">How much room do they need?</a></li>
            <li><a href="#malefemale">Should I get a male or female?</a></li>
            <li><a href="#hotweather">How do they handle the hot weather?</a></li>
            <li><a href="#rescued">What is a rescued dog?</a></li>
            <li><a href="#rescue">What is a rescue?</a></li>
            <li><a href="#money">How much money do you make, doing rescues?</a></li>
            <li><a href="#whyDoIt">So, why do you do rescue work?</a></li>
            <li><a href="#baddogs">Do you accept mean or aggressive dogs into rescue?</a></li>
        </ul>
        <br />    
          <p><a name="eat" id="eat"></a><h3>HOW MUCH DO THEY EAT?</h3> A  Saint Bernard will not eat you out of house and home. The fact is a  Saint Bernard can be raised and maintained on no more food than  required for other more active breeds. Since Saints are basically  placid dogs, they generally require less food per pound of body weight  than smaller, more active breeds.<br /><br /><a href="" name="top">Back to Top</a><br /><br /></p>
          <p><a name="weight" id="weight"></a><h3>HOW MUCH DO THEY WEIGH?</h3> Saint  puppies weigh about one and one-half pounds at birth and grow rapidly  during the first year, although it may take as long as three years  before they reach full maturity. Adult males may reach a height of  28-32 inches at the shoulder and will normally weigh between 140 and  180 pounds. Females are somewhat smaller at about 26-28 inches at the  shoulder and typically range from 120 to 140 pounds.<br /><br /><a href="" name="top">Back to Top</a><br /><br /></p>
          <p><a name="children" id="children"></a><h3>ARE THEY GOOD WITH CHILDREN?</h3> A  Saint with the proper temperament will have an understanding of a  child's way, and will be amazingly careful not to injure a child. They  are excellent supervised baby-sitters and companions. Naturally, a  child must never be allowed to torment any dog, regardless of breed,  and children should never be left unsupervised with any dog. A Saint  without this proper temperament is a danger, and should be regarded as  such.<br /><br /><a href="" name="top">Back to Top</a><br /><br /></p>
          <p><a name="train" id="train"></a><h3>ARE THEY EASY TO TRAIN?</h3> Because of the size of  the animal, the Saint Bernard MUST be trained and this must be done  early in his life. Fortunately, Saints are eager to please and will  begin responding to commands as soon as they understand what you want  of them. Their level of intelligence and willingness to co-operate make  them a joy to train and spend time with!<br /><br /><a href="" name="top">Back to Top</a><br /><br /></p>
          <p><a name="shed" id="shed"></a><h3>DO THEY SHED?</h3> Yes.  Twice a year, usually in Spring and Fall, they lose much of their coats  to help them adjust to the changing seasons (Saint people call this  blowing the coat... the phrase is very descriptive!) For the remainder  of the year there is seldom much annoyance from shedding.<br /><br /><a href="" name="top">Back to Top</a><br /><br /></p>
          <p><a name="drool" id="drool"></a><h3>DO THEY DROOL?</h3> Yes.  Depending on the weather, the level of excitement, and the shape of the  dog's jowls, most Saints will drool on occasion. Technically, there is  no such thing as a dry mouthed Saint, but most Saints do not drool to  an offensive degree.<br /><br /><a href="" name="top">Back to Top</a><br /><br /></p>
          <p><a name="glands" id="glands"></a><h3>IS IT OK TO CLIP A SAINTS SALIVA GLANDS?</h3> Absolutely  not! Saliva helps dogs digest their food. By clipping the saliva  glands, you put the dog a great risk of bloat as the kibble is not able  to digest as easily. The only way a dog is able release body heat is by  sweating, but dogs don't sweat like people. They sweat through the pads  of their feet and by panting, which produces saliva. If you clip the  glands, you take away their only mechanism to cool off. If you dislike  the drool, look for other tighter-lipped breeds.<br /><br /><a href="" name="top">Back to Top</a><br /><br /></p>
          <p><a name="watchdog" id="watchdog"></a><h3>ARE THEY GOOD WATCHDOGS?</h3> The  Saint's size and bark will discourage most intruders, yet he will learn  to recognize your friends and receive them cordially. If an intruder  gets by the size and barks, your Saint may decide to lead him straight  to the family silver since he would much prefer to be a friend to all.  The one exception to this is when a member of the family is being  threatened. The Saint's instinct to protect those he loves becomes very  apparent at this time.<br /><br /><a href="" name="top">Back to Top</a><br /><br /></p>
          <p><a name="shorthair" id="shorthair"></a><h3>WHY DO SOME SAINT BERNARDS HAVE SHORT HAIR?</h3> The  original Saint Bernards were all short-haired dogs. Over 150 years ago,  the Monks in Switzerland found it necessary to bring some new blood  into their breeding and interbred the long Newfoundland with their  Saints. Today, the influence of that breeding is still with us and we  have both long and short-haired Saint Bernards. Both are of equal value.<br /><br /><a href="" name="top">Back to Top</a><br /><br /></p>
          <p><a name="room" id="room"></a><h3>HOW MUCH ROOM DO THEY NEED?</h3> The  Saint by nature does not require acres and acres to roam. They are not  as active or nervous as some breeds and are content to remain close to  home for the most part. Consequently, a small fenced yard or kennel run  is enough just so long as there is some place for regular exercise. The  apartment dweller must be walked frequently to make up for the exercise  he would normally take at his leisure.<br /><br /><a href="" name="top">Back to Top</a><br /><br /></p>
          <p><a name="malefemale" id="malefemale"></a><h3>SHOULD I GET A MALE OR A FEMALE?</h3> This  is strictly a matter of personal preference. Both are equal in pet  qualities. The male, being larger, is more impressive when first  viewed. The female, however, must be considered his equal in all other  respects. Modern veterinary practice recommends neutering of  non-breeding animals of both sexes as a means to a healthier, better  pet.<br /><br /><a href="" name="top">Back to Top</a><br /><br /></p>
          <p><a name="hotweather" id="hotweather"></a><h3>HOW DO THEY HANDLE THE HOT WEATHER?</h3> The dog will  do well as long as there is a cool dry place to nap and plenty of fresh  cool water. He will cut down both his food intake and his amount of  activity. It must be remembered that going from an air-conditioned  place into the boiling heat can be disastrous. Abrupt changes in  temperature are extremely hard on a Saint.<br /><br /><a href="" name="top">Back to Top</a><br /><br /></p>
          <p><a name="rescued" id="rescued"></a><h3>WHAT IS A RESCUED DOG?</h3> There  is a lot of confusion over this, because Saints are bred to perform  rescues from avalanches. A rescued dog doesn't do this. A rescued dog  has been abandoned by his/her family, for any one of a thousand reasons  - he got too big; he drools; he sheds; he plays rough with the kids;  he's dug up the back yard; he barks; the owners want a pool, but can't  have one with the dog living back there; he's unruly; he's not  housetrained, etc.<br /><br /><a href="" name="top">Back to Top</a><br /><br /></p>
          <p><a name="rescue" id="rescue"></a><h3>WHAT IS A RESCUE?</h3> A rescue (or  rescue worker) takes in the above-mentioned abandoned dog, and teaches  him manners, provides medical attention (spay/neuter, bringing shots  up-to-date, heartworm testing and treatment, etc.), provides security  and love to dogs that, many times have not had any real human contact  in all the years they've spent chained to the doghouse in the backyard.  Rescue workers take in the dogs that have been abused and neglected to  the point where the general public thinks they're hopeless cases and we  work with these dogs to help them forgive and forget their  mistreatment. Dogs are incredibly forgiving creatures... they just need  a gentle hand to remind them that they can forgive.<br /><br /><a href="" name="top">Back to Top</a><br /><br /></p>
          <p><a name="money" id="money"></a><h3>HOW MUCH MONEY DO YOU MAKE, DOING RESCUE?</h3> Those  people doing rescue aren't doing it for money. Do the math: Call your  vet, and ask how much he charges to spay/neuter a 150-pound dog. Then,  ask him how much he charges to treat that same dog for heartworm. While  you're at it, ask the cost of heartworm preventative, worming, the  basic shots including rabies, and the office exam. Then, remember that  we also feed and re-train these dogs while they're in our possession -  which sometimes takes months. This is why rescues request an adoption  donation. Every once in a while, a dog comes into rescue not needing  anything done before placement; they're rare, but they do come along  occasionally. These dogs help to pay the way for the dogs needing  intensive treatment or is paid by the rescue worker out-of-pocket. Most  rescues operate in the red... we rely on the donations of necessities  to continue in our work.<br /><br /><a href="" name="top">Back to Top</a><br /><br /></p>
          <p><a name="whyDoIt" id="whyDoIt"></a><h3>SO, WHY DO YOU DO RESCUE WORK?</h3> For  the same reason that many people work with children or elderly people  on a volunteer basis: we love these dogs. They're defenseless  creatures (yes, really!). They didn't ask to be brought into this world  and only ask to be allowed to adore their people... they ask very  little in return. We feel a basic responsibility to atone for the  maltreatment of these dogs by their owners. Humans domesticated dogs  for their own use - it's our responsibility to demand humane treatment  and responsible ownership.<br /><br /><a href="" name="top">Back to Top</a><br /><br /></p>
          <p><a name="baddogs" id="baddogs"></a><h3>DO YOU ACCEPT MEAN OR AGGRESSIVE DOGS INTO RESCUE?</h3> Sadly,  no. Those dogs deemed aggressive (in any way) are not adoptable. There  are many reasons for this: There are many, many non-aggressive Saints  that are dying in shelters for lack of funding, space, and volunteers -  it's not fair to them, to take in dogs that have a known bite history.  It's also not fair to the rescue workers and their families and dogs to  ask them to cope with a dog with known aggressive tendencies, and it's  not fair to the adoptive families for the rescue workers to offer these  dogs for adoption. Every aggressive dog that is adopted out sacrifices  both the integrity of the breed, and the credibility of the  breed-rescue. It's not fair to anyone.<br /><br /><a href="" name="top">Back to Top</a><br /><br /></p>
    </div> <!--ENDS CONTENT_MAIN DIV-->
    
<?php require_once("includes/site_info.php"); ?>